language: bash

sudo: required

services:
  - docker

install:
  - cp ./emqx.io.ldif ./emqx.schema ./.ci/emqx-ldap
  - docker-compose -f ./.ci/docker-compose.yml -p tests up -d --build

before_script:
  - docker exec -i tests_erlang_1 sh -c "sed -i '/auth.ldap.servers/c auth.ldap.servers = ldap_server' ./emqx_auth_ldap/etc/emqx_auth_ldap.conf"

script:
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap compile"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap eunit"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap ct"

after_script:
  - docker-compose -f ./.ci/docker-compose.yml -p tests down 
  - rm -f ./.ci/emqx-ldap/emqx.io.ldif ./.ci/emqx-ldap/emqx.schema
