name: Run test cases

on: [push, pull_request]

jobs:    
    run_test_cases:
        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
            
        steps:
            - uses: actions/checkout@v1
            - name: prepare
              run: |
                cp ./emqx.io.ldif ./emqx.schema .github/workflows/emqx-ldap
                docker-compose -f .github/workflows/docker-compose.yml -p tests up -d --build
            - name: run test cases
              run: |
                docker exec -i tests_erlang_1 sh -c "sed -i '/auth.ldap.servers/c auth.ldap.servers = ldap_server' ./emqx_auth_ldap/etc/emqx_auth_ldap.conf"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap xref"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap eunit"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap ct"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_ldap cover"
            - uses: actions/upload-artifact@v1
              if: always()
              with:
                name: logs
                path: _build/test/logs
            - uses: actions/upload-artifact@v1
              with:
                name: cover
                path: _build/test/cover

